<a href="https://colab.research.google.com/github/tszhang120/python100days/blob/main/%E8%AF%AD%E6%B3%95%E5%9F%BA%E7%A1%80/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[1.0312e-32, 4.5901e-41, 1.0312e-32],
        [4.5901e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 7.7052e+31, 7.2148e+22],
        [1.5766e-19, 1.0256e-08, 4.1019e-08]])


In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.4471, 0.5235, 0.6333],
        [0.4120, 0.2693, 0.6867],
        [0.9530, 0.2031, 0.6319],
        [0.4128, 0.8653, 0.9002],
        [0.4167, 0.3839, 0.6800]])


In [6]:
x=torch.zeros(5,3,dtype=torch.long)

In [7]:
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x=torch.tensor([5.5,3])

In [9]:
print(x)

tensor([5.5000, 3.0000])


In [10]:
x=torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
